const data = {
    products: [
        {
            _id:'1',
            name:'Water can',
            category:'Misc',
            image:'../img/1.jpg',
            price:1000,
            contentInStock: 10,
            brand:'WatersInc',
            rating:1.5,
            numReviews: 10,
            description: 'Best water can',
        },
        {
            _id:'2',
            name:'Scrissors',
            category:'Scissors',
            image:'../img/2.jpg',
            price:500,
            contentInStock: 10,
            brand:'ScissorsInc',
            rating:4.5,
            numReviews: 10,
            description: 'Best scissors',
        },
        {
            _id:'3',
            name:'Substrate',
            category:'Substrate',
            image:'../img/3.jpg',
            price:1200,
            contentInStock: 10,
            brand:'SubstrateInc',
            rating:2,
            numReviews: 10,
            description: 'Best substrate',
        },
        {
            _id:'4',
            name:'Oil',
            category:'Health',
            image:'../img/4.jpg',
            price:2500,
            contentInStock: 0,
            brand:'Cogordito',
            rating:3,
            numReviews: 10,
            description: 'Best Oil',
        },
        {
            _id:'5',
            name:'Hand cream',
            category:'Health',
            image:'../img/5.jpg',
            price:700,
            contentInStock: 0,
            brand:'Cogordito',
            rating: 4,
            description: 'Best cream',
            numReviews: 32,
        },
        {
            _id:'6',
            name:'Shampoo',
            category:'Health',
            image:'../img/6.jpg',
            price:1350,
            contentInStock: 10,
            brand:'Cogordito',
            rating: 4,
            numReviews: 32,
            description:'Best Shampoo description'
        },
    ]
};

export default data;